# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      echo 'init script'
      sudo apt-get update && sudo apt-get -y upgrade
      sudo apt-get -y install ffmpeg texlive-latex-extra python3-dev
      pip3 install --upgrade pip
      pip3 install manim
#  - command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
